campaign:
  name: "tcdb_vhh_paper_repro"
  description: "Reproduce TcdB Frizzled-site VHH from Bennett et al. 2025"
  version: "1.0"

target:
  pdb_id: "6C0B"
  chain_id: "A"
  epitope_residues: [1285, 1286, 1287, 1288, 1340, 1341, 1342, 1343, 1344, 1400, 1401, 1402]
  hotspot_residues: [1286, 1340, 1342, 1401]
  truncation:
    enabled: true
    buffer_angstroms: 10.0

antibody:
  format: "vhh"
  framework: "builtin:NbBCII10"
  cdr_loops:
    H1: "7"
    H2: "6"
    H3: "5-13"

pipeline:
  rfdiffusion:
    num_designs: 9000
  proteinmpnn:
    sequences_per_backbone: 5
    temperature: 0.2
  rf2:
    recycling_iterations: 10

filtering:
  pae_threshold: 10.0
  rmsd_threshold: 2.0

output:
  directory: "./results/tcdb_vhh_paper_repro"
  top_n_candidates: 50
  report_format: "both"
  export_pdbs: true
  keep_intermediates: true

# Validation targets:
# - Binders at 5.5 uM (RBD) to 262 nM (H2)
# - Neutralization EC50 = 460 nM (TcdB_H2)
# - Cryo-EM resolution 3.0-4.6 A
