"""Generate campaign summary reports."""

from __future__ import annotations

import html as html_mod
import logging
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import pandas as pd

from harness.config.schema import CampaignConfig

logger = logging.getLogger(__name__)


def generate_report(
    ranked: pd.DataFrame,
    all_scores: pd.DataFrame,
    config: CampaignConfig,
    output_dir: Path,
) -> Path:
    """Generate an HTML and/or CSV campaign report."""
    output_dir.mkdir(parents=True, exist_ok=True)
    fmt = config.output.report_format.lower()

    csv_path = output_dir / "ranked_candidates.csv"
    ranked.to_csv(csv_path, index=False)
    logger.info("Wrote CSV report → %s", csv_path)

    if fmt in ("html", "both"):
        html_path = output_dir / "report.html"
        _write_html(ranked, all_scores, config, html_path)
        logger.info("Wrote HTML report → %s", html_path)
        return html_path

    return csv_path


def _write_html(
    ranked: pd.DataFrame,
    all_scores: pd.DataFrame,
    config: CampaignConfig,
    path: Path,
) -> None:
    top_n = config.output.top_n_candidates
    top = ranked.head(top_n)

    total = len(all_scores)
    passed = len(ranked)
    pass_rate = (passed / total * 100) if total else 0

    display_cols = [c for c in ["rank", "tag", "pae", "rmsd", "ddg", "composite_score"] if c in top.columns]
    table_html = top[display_cols].to_html(index=False, float_format="%.3f", classes="data")

    # Score distribution summary
    summary_rows = ""
    for col in ["pae", "rmsd", "ddg"]:
        if col in all_scores.columns:
            s = all_scores[col]
            summary_rows += (
                f"<tr><td>{col}</td>"
                f"<td>{s.min():.2f}</td>"
                f"<td>{s.median():.2f}</td>"
                f"<td>{s.mean():.2f}</td>"
                f"<td>{s.max():.2f}</td></tr>\n"
            )

    esc = html_mod.escape
    html = f"""<!DOCTYPE html>
<html><head>
<title>Campaign Report: {esc(config.campaign.name)}</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 960px; margin: 2em auto; }}
h1 {{ border-bottom: 2px solid #333; padding-bottom: 0.3em; }}
table.data {{ border-collapse: collapse; width: 100%; }}
table.data th, table.data td {{ border: 1px solid #ccc; padding: 6px 10px; text-align: right; }}
table.data th {{ background: #f4f4f4; }}
.meta {{ background: #f8f8f8; padding: 1em; border-radius: 4px; margin-bottom: 1.5em; }}
</style>
</head><body>
<h1>Campaign: {esc(config.campaign.name)}</h1>
<p>{esc(config.campaign.description or '')}</p>

<div class="meta">
<strong>Target</strong>: {config.target.pdb_id or config.target.pdb_file} chain {config.target.chain_id}<br>
<strong>Format</strong>: {config.antibody.format} / {config.antibody.framework}<br>
<strong>Designs</strong>: {config.pipeline.rfdiffusion.num_designs}<br>
<strong>Sequences/backbone</strong>: {config.pipeline.proteinmpnn.sequences_per_backbone}<br>
</div>

<h2>Filtering Summary</h2>
<p><strong>{passed}</strong> / {total} designs passed filters ({pass_rate:.1f}%)</p>
<p>Thresholds: pAE &lt; {config.filtering.pae_threshold}, RMSD &lt; {config.filtering.rmsd_threshold}
{f', ddG &lt; {config.filtering.ddg_threshold}' if config.filtering.ddg_threshold else ''}</p>

<h2>Score Distributions (All Designs)</h2>
<table class="data">
<tr><th>Metric</th><th>Min</th><th>Median</th><th>Mean</th><th>Max</th></tr>
{summary_rows}
</table>

<h2>Top {min(top_n, len(top))} Candidates</h2>
{table_html}

<h2>PyMOL Commands (Top 10)</h2>
<pre>
{"".join(f'load candidates/{row["tag"]}.pdb, {row["tag"]}{chr(10)}' for _, row in top.head(10).iterrows() if "tag" in row) if "tag" in top.columns else "# No candidates"}
</pre>

<footer><p>Generated by rfab-harness</p></footer>
</body></html>"""

    path.write_text(html)
