campaign:
  name: "c5_vhh_v1"
  description: "De novo VHH targeting complement C5 cleavage site (PNH / aHUS)"
  version: "1.0"

target:
  pdb_id: "3CU7"
  chain_id: "A"
  epitope_residues: [91, 94, 95, 97, 99, 102, 150, 156, 160, 163, 164, 168, 170]
  hotspot_residues: [94, 97, 160, 163]
  truncation:
    enabled: true
    buffer_angstroms: 10.0

antibody:
  format: "vhh"
  framework: "builtin:NbBCII10"
  cdr_loops:
    H1: "7"
    H2: "6"
    H3: "5-13"

pipeline:
  rfdiffusion:
    num_designs: 10000

filtering:
  pae_threshold: 10.0
  rmsd_threshold: 2.0
  ddg_threshold: -20.0

output:
  directory: "./results/c5_vhh_v1"
  top_n_candidates: 50
  report_format: "both"
  export_pdbs: true

# CHALLENGE: Very large target (~190 kDa), conformational dynamics
# VHH advantage: smaller size may access cleavage-site pocket better than mAb
