campaign:
  name: "egfr_cetuximab_vhh_v1"
  description: "De novo VHH targeting EGFR Domain III (cetuximab epitope). For GBM (57% amplified), MPNST (28% amplified), PDAC (KRAS-WT). Template: 1YY9 (cetuximab Fab, 2.6A)."
  version: "1.0"

target:
  pdb_id: "1YY9"
  chain_id: "A"
  epitope_residues: [351, 353, 355, 357, 358, 359, 361, 382, 384, 386, 388, 389, 390, 391, 408, 410, 412, 414, 416, 465, 467, 469, 470, 471, 473, 475, 476, 489, 491, 493]
  hotspot_residues: [357, 382, 412, 467, 489]
  truncation:
    enabled: true
    buffer_angstroms: 10.0

antibody:
  format: "vhh"
  framework: "builtin:NbBCII10"
  cdr_loops:
    H1: "7"
    H2: "6"
    H3: "5-13"

pipeline:
  rfdiffusion:
    num_designs: 10000
    seed: 44

filtering:
  pae_threshold: 10.0
  rmsd_threshold: 2.0
  ddg_threshold: -20.0

compute:
  gpus: 1
  memory_gb: 40

output:
  directory: "./results/cancer_drivers/egfr_cetuximab_vhh_v1"
  top_n_candidates: 50
  report_format: "both"
  export_pdbs: true
